[workspace]
resolver = "3"
members = ["crates/*", "probes/interpose-probe"]
exclude = ["shims"]

[workspace.package]
version = "3.0.0"
edition = "2024"
rust-version = "1.88"
license = "Apache-2.0"
authors = ["Bowan Foryt <bowan@valstad.com>"]
repository = "https://github.com/valstad-shipworks/snare"
